// SPDX-FileCopyrightText: The Plinky Authors
// SPDX-License-Identifier: 0BSD

import { gunzipSync, strFromU8 } from "fflate";
import type { Score } from "./catalog";

// The finger-exercise catalogue — scales and arpeggios in every key and form,
// generated by dev/gen-exercises.mts. The metadata manifest is small and always
// loaded (so exercises are always browsable); all the MusicXML ships in one gzipped
// pack fetched once, so every exercise is available offline after a single request.

export type ExerciseMeta = {
    id: string;
    title: string;
    grade: number;
    tempo: number;
    beatsPerBar: number;
};

const MANIFEST_URL = "/exercises/manifest.json";
const PACK_URL = "/exercises/pack.json.gz";

let manifestCache: ExerciseMeta[] | null = null;
let packCache: Record<string, string> | null = null;
let packPromise: Promise<Record<string, string>> | null = null;

export async function loadExerciseManifest(): Promise<ExerciseMeta[]> {
    if (manifestCache) {
        return manifestCache;
    }
    try {
        const response = await fetch(MANIFEST_URL);
        manifestCache = response.ok ? ((await response.json()) as ExerciseMeta[]) : [];
    } catch {
        manifestCache = [];
    }
    return manifestCache;
}

// Fetch + decompress the pack once; concurrent callers share the one request.
function loadPack(): Promise<Record<string, string>> {
    if (packCache) {
        return Promise.resolve(packCache);
    }
    if (!packPromise) {
        packPromise = (async () => {
            try {
                const response = await fetch(PACK_URL);
                if (!response.ok) {
                    return {};
                }
                const bytes = new Uint8Array(await response.arrayBuffer());
                return JSON.parse(strFromU8(gunzipSync(bytes))) as Record<string, string>;
            } catch {
                return {};
            }
        })().then((pack) => {
            packCache = pack;
            return pack;
        });
    }
    return packPromise;
}

export async function getExerciseXml(id: string): Promise<string | null> {
    return (await loadPack())[id] ?? null;
}

// Resolve an exercise id to a playable Score; null if unknown. The play flow falls
// back to this for ids that are neither bundled, user, nor song scores.
export async function resolveExercise(id: string): Promise<Score | null> {
    const meta = (await loadExerciseManifest()).find((exercise) => exercise.id === id);
    if (!meta) {
        return null;
    }
    const xml = await getExerciseXml(id);
    if (xml === null) {
        return null;
    }
    return {
        id: meta.id,
        title: meta.title,
        composer: "",
        description: "",
        xml,
        tempo: meta.tempo,
        beatsPerBar: meta.beatsPerBar,
        bundled: true,
    };
}
