// SPDX-FileCopyrightText: The Plinky Authors
// SPDX-License-Identifier: AGPL-3.0-or-later

// Bakes the prerender index the person pages are built from: the composers the shipped
// catalogue credits with enough pieces to earn a static document, as slug → canonical
// name and how many pieces they hold.
//
// It exists because a person page has to know the composer's name BEFORE the catalogue
// manifest loads. The page's title, its description and its Person structured data are
// all written during prerender, in Node, with no network — so without a baked index a
// catalogue composer's static document carries a name guessed back from the URL slug
// ("Gabriel Faure" for Fauré) and no structured data at all. With it, every composer
// page is a real, crawlable entity in the static HTML, and the piece list still fills
// in from the manifest on the client exactly as before.
//
// Only the prerendered composers are listed, not all 542. Below the floor a page is
// rendered on the client, where the manifest supplies the name anyway a moment later —
// so an entry there would buy nothing and cost every visitor the bytes, since the
// index ships in the person route's chunk.
//
// Derived, never hand-edited: the same canonicalisation the app uses at runtime
// (core/person) is what runs here, so the index cannot disagree with the links that
// point into it. Run through `npm run songs:bake`; `--check` is the CI guard.

import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { canonicalComposer, personSlug } from "../core/person";

// The formatter, over a string. `--stdin-file-path` is what tells biome which rules apply,
// and it writes the formatted source to stdout.
function format(source: string): string {
    return execFileSync("npx", ["biome", "format", `--stdin-file-path=${INDEX}`], {
        input: source,
        encoding: "utf8",
    });
}

const SONGS = "public/songs/manifest.json";
const EXERCISES = "public/exercises/manifest.json";
const INDEX = "core/peopleIndex.ts";

// A composer page listing one or two pieces is thin: little for a reader, little for a
// crawler, and 601 of them multiplied by every locale is a build cost with nothing on
// the other side of it. Below the floor a composer still has a working page — it is
// simply rendered on the client like any other, rather than prerendered.
export const PRERENDER_MIN_PIECES = 3;

type CataloguePiece = { composer?: string };

const HEADER = `// SPDX-FileCopyrightText: The Plinky Authors
// SPDX-License-Identifier: AGPL-3.0-or-later

// GENERATED by dev/bake-people.mts — do not edit. Run \`npm run songs:bake\`.
//
// The composers whose pages are prerendered, as their URL slug mapped to the canonical
// spelling of their name and how many pieces they hold. The person route reads this so
// a page knows whose it is at prerender time, before any manifest has loaded; the
// pieces themselves still arrive from the manifest on the client.
//
// A composer the catalogue credits with fewer pieces is deliberately absent: their page
// renders on the client, where the manifest names them anyway, and listing them here
// would ship every visitor bytes that buy nothing.

export type PersonEntry = { name: string; pieces: number };

export const PEOPLE_INDEX: Record<string, PersonEntry> = `;

const FOOTER = `;

// The canonical name for a slug, or null when the catalogue credits nobody by it —
// a user-imported score's composer, or a slug typed by hand. Own-property only: a bare
// lookup answers for "constructor", "toString" and every other name on Object's
// prototype, so /person/constructor would open a page for a function.
export function indexedPerson(slug: string): PersonEntry | null {
    return Object.hasOwn(PEOPLE_INDEX, slug) ? (PEOPLE_INDEX[slug] as PersonEntry) : null;
}
`;

async function readPieces(path: string): Promise<CataloguePiece[]> {
    const parsed: unknown = JSON.parse(await readFile(path, "utf8"));
    return Array.isArray(parsed) ? (parsed as CataloguePiece[]) : [];
}

export async function bakePeopleIndex(check: boolean): Promise<boolean> {
    const pieces = [...(await readPieces(SONGS)), ...(await readPieces(EXERCISES))];

    const index = new Map<string, { name: string; pieces: number }>();
    for (const piece of pieces) {
        const credit = piece.composer ?? "";
        const slug = personSlug(credit);
        // personSlug returns "" for an attribution that names a tradition rather than a
        // human ("Traditional", "Anonymous"): those have no page, so no entry.
        if (!slug) {
            continue;
        }
        const entry = index.get(slug);
        if (entry) {
            entry.pieces += 1;
        } else {
            index.set(slug, { name: canonicalComposer(credit), pieces: 1 });
        }
    }

    // Sorted by slug so the generated file's diff shows what actually changed rather
    // than reshuffling on every catalogue import.
    const sorted = [...index.entries()]
        .filter(([, entry]) => entry.pieces >= PRERENDER_MIN_PIECES)
        .sort(([left], [right]) => left.localeCompare(right));
    // Emitted the way the formatter would write it, because both gates read this file:
    // `songs:bake --check` compares it byte for byte against this string, and `lint` runs
    // the formatter over the tree. Compact JSON satisfies the first and fails the second,
    // and a run of the formatter over a generated file then breaks the first permanently —
    // which is a trap nobody can be expected to remember, so the generator avoids it.
    const body = `{\n${sorted
        .map(
            ([slug, entry]) =>
                `    ${JSON.stringify(slug)}: { name: ${JSON.stringify(entry.name)}, pieces: ${entry.pieces} },`,
        )
        .join("\n")}\n}`;
    // Run through the project's own formatter rather than guessed at. Both gates read this
    // file — `--check` compares it byte for byte against this string, and `lint` runs the
    // formatter over the whole tree — so the two agree only if the generator emits exactly
    // what the formatter would. Matching its line-wrapping by hand would mean
    // reimplementing it, and a formatter run over a generated file would then break the
    // check permanently, which is a trap nobody can be expected to remember.
    const baked = format(`${HEADER}${body}${FOOTER}`);

    if (check) {
        const current = await readFile(INDEX, "utf8").catch(() => "");
        if (current !== baked) {
            console.error(`${INDEX} is stale — the catalogue credits composers it does not list.`);
            return false;
        }
        console.log(`Composer index is baked: ${sorted.length} prerendered composers.`);
        return true;
    }

    await writeFile(INDEX, baked);
    console.log(
        `Composer index: ${index.size} composers credited, ${sorted.length} with ${PRERENDER_MIN_PIECES}+ pieces (prerendered).`,
    );
    return true;
}
