// SPDX-FileCopyrightText: The Plinky Authors
// SPDX-License-Identifier: AGPL-3.0-or-later

// Writes the whole changelog beside the site, for the /news page to fetch.
//
// The page's own document carries the newest releases (core/newsLatest.ts, generated by
// dev/changelog.mts), which is what a crawler and a returning player come for. The
// archive is a hundred and sixty kilobytes and belongs nowhere near a bundle, so it is a
// file the page asks for once somebody is reading — the same arrangement the catalogue
// manifest and the composers' details already use.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { parse } from "yaml";
import { parseChangelog } from "../core/changelog.ts";

const OUT = "build/client";
const SOURCE = "changelog.yaml";

export function newsFeed(): { releases: unknown[]; entries: number } {
    const { releases, problems } = parseChangelog(parse(readFileSync(SOURCE, "utf8")));
    if (problems.length > 0) {
        throw new Error(`${SOURCE}:\n- ${problems.join("\n- ")}`);
    }
    return {
        releases,
        entries: releases.reduce((count, release) => count + release.entries.length, 0),
    };
}

export function writeNewsFeed(out = OUT): { releases: number; entries: number } {
    const { releases, entries } = newsFeed();
    mkdirSync(out, { recursive: true });
    writeFileSync(`${out}/news.json`, JSON.stringify(releases));
    return { releases: releases.length, entries };
}

if (process.argv[1]?.endsWith("gen-news-feed.mts")) {
    const { releases, entries } = writeNewsFeed();
    console.log(`${OUT}/news.json: ${releases} releases, ${entries} entries.`);
}
