// SPDX-FileCopyrightText: The Plinky Authors
// SPDX-License-Identifier: 0BSD

// One-shot migration: re-id the already-imported catalogue in place to content-fingerprint
// ids, moving each .mxl into its per-licence subdirectory (public/songs/<licence>/<id>.mxl).
// No re-import — it reads the existing public/songs, so the 30 GB PDMX dataset and the
// remote corpora are not touched. The import scripts produce the same scheme for future
// imports; this just migrates what is already committed. Run: `npm run songs:reid`.

import { readFileSync } from "node:fs";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { strFromU8, unzipSync } from "fflate";
import { licenseDir } from "../core/attribution.ts";
import { songId } from "../core/songId.ts";

const OUT = "public/songs";

type SongMeta = { id: string; license: string; [key: string]: unknown };

function readMxl(path: string): string {
    const entries = unzipSync(new Uint8Array(readFileSync(path)));
    const container = strFromU8(entries["META-INF/container.xml"] ?? new Uint8Array());
    const root =
        container.match(/full-path="([^"]+)"/)?.[1] ??
        Object.keys(entries).find((name) => name.endsWith(".xml") && !name.startsWith("META-INF"));
    if (!root || !entries[root]) {
        throw new Error("no rootfile");
    }
    return strFromU8(entries[root]);
}

async function main() {
    const manifest: SongMeta[] = JSON.parse(await readFile(`${OUT}/manifest.json`, "utf8"));
    const seen = new Set<string>();
    const out: SongMeta[] = [];
    let dropped = 0;
    for (const song of manifest) {
        const oldPath = `${OUT}/${song.id}.mxl`;
        let xml: string;
        try {
            xml = readMxl(oldPath);
        } catch {
            dropped++;
            continue;
        }
        const id = songId(xml);
        if (seen.has(id)) {
            // Identical content already kept — drop this duplicate (e.g. the same piece
            // present under two sources, or a repeated harmonization).
            await rm(oldPath, { force: true });
            dropped++;
            continue;
        }
        seen.add(id);
        const dir = `${OUT}/${licenseDir(song.license)}`;
        await mkdir(dir, { recursive: true });
        await rename(oldPath, `${dir}/${id}.mxl`);
        out.push({ ...song, id });
    }
    // The seed is regenerated by songs:bake from the manifest, so only the manifest ids
    // need rewriting here.
    await writeFile(`${OUT}/manifest.json`, JSON.stringify(out));
    console.log(`Re-ided ${out.length} songs; ${dropped} content-duplicates dropped.`);
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
